version: '3'

services:
    lt-scheduler:
        volumes:
            - ./:/usr/app/main
            # Little trick to not mount the host node_modules to the container https://stackoverflow.com/a/37898591/1335209
            - /usr/app/main/node_modules
        build:
            args:
                - ENVIRONMENT=development
        env_file:
            - dev.lt-scheduler.env
            - dev.lt-scheduler.local.env
        ports:
            # Port needed to debug a Node.js process
            - 9230:9230
        command: npm run dev
