version: '3'

services:
    lt-scheduler:
        image: dragondgold/lt-scheduler
        container_name: lt-scheduler
        build:
            context: .
            dockerfile: ./Dockerfile
        networks:
            - lt-scheduler

    redis:
        image: redis:6.0-alpine
        container_name: lt-scheduler-redis
        volumes:
            - ./redis.conf:/usr/local/etc/redis/redis.conf
        networks:
            - lt-scheduler
        ports:
            - 6379:6379
        command: redis-server /usr/local/etc/redis/redis.conf

    postgres:
        image: postgres:12.4-alpine
        container_name: lt-scheduler-postgres
        volumes:
            - ./init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
            - ./pgdata:/var/lib/postgresql/data
        networks:
            - lt-scheduler
        ports:
            - 5433:5432
        environment:
            POSTGRES_PASSWORD: 12345678

networks:
    lt-scheduler:
        driver: bridge
